### ISSUE TITLE
Add support to Python 3.7

### ISSUE THREAD

**Issue by ivancrneto** [ivancrneto/pymox#4]

**Comment by dnegreira** [comment]
Hi Ivan, I can help you with this, can I work on it?

**Comment by ivancrneto** [comment]
Sure, thanks, go for it!

**Comment by sgpy** [comment]
@ivancrneto Please [review & comment](https://github.com/glasser/pymox/pull/61#issuecomment-460240429)

**Comment by sgpy** [comment]
@ivancrneto Do you have any plans for merge this with the main project?

**Comment by sgpy** [comment]
@ivancrneto I was able to port __lettuce__ onto __py3__. __pymox__ sure is handy mate. I saw one  problem in your codebase, but i patched it to get around it for now.

**Comment by no-identd** [comment]
You might wanna check out https://github.com/openstack/mox3 by @openstack

**Comment by ivancrneto** [comment]
@sgpy can you please submit a pull request? That would be great!

**Comment by ivancrneto** [comment]
@no-identd I checked them, thanks! They don't support python 2.

**Comment by ivancrneto** [comment]
@sgpy @no-identd I'm closing the issue since version 1.0.0 it supports Python 3.7-3.11: https://github.com/ivancrneto/pymox/releases/tag/v1.0.0
